### ISSUE TITLE
Product_Model shoud be KB2000

### ISSUE THREAD

**Issue by SeimoDev** [Kscope-Devices/android_device_oneplus_kebab#1]
Some apps couldn't spot the device with KB2003 or KB2005(like KB2003 can't use HDR in Bilibili but KB2000 can)

So,I think maybe KB2000 is a better choices?

However,thanks for your great work!

**Comment by libxzr** [comment]
https://github.com/Kscope-Devices/android_device_oneplus_sm8250-common/blob/f4c72e0857b1fb166998fa45587a7e139b9fc8c7/init/init_sm8250.cpp#L138
